# worker_node/utils/settings.yml

# System-wide settings
system:
  type: "simulation" # Type of the system: 'production' or 'simulation'
  main_interface: "en0" # Network interface used for communication

# MQTT Broker Configuration
mqtt:
  broker: "mqtt-broker" # IP address or hostname of the MQTT broker
  port: 1883 # Default MQTT port
  keepalive: 60 # Keep-alive period in seconds

# Coordinator Daemon Configuration
coordinatord:
  worker_dest_port: 5001 # Destination port for worker nodes
  monitor_dest_port: 5002 # Destination port for monitor nodes
  listen_port: 6000 # Listening port for the coordinator
  send_port: 6001 # Port for sending messages
  broadcast_port: 6002 # Port for broadcasting messages
  udp_port: 54321
  crma_ip: "127.0.0.1"
  crma_udp_port: 12345
  max_retries: 20
  task_queue_size: 10
  register_message: "REGISTER"
  ack_message: "ACK"


builderd:
  monitoring_stack:
  - container_name: "prometheus"
    image: "bishwo007/prometheus:v1.0"
    ports:
      "9090": "9090"
    networks:
    - "monitoring-net"

  - container_name: "node-exporter"
    image: "prom/node-exporter:latest"
    ports:
      "9100": "9100"
    networks:
    - "monitoring-net"

  - container_name: "cadvisor"
    image: "gcr.io/cadvisor/cadvisor:latest"
    ports:
      "8080": "8080"
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    privileged: true
    networks:
    - "monitoring-net"

queryd:
  send_port: 10410 # port for sending out UDP "specialized" packets to ONOS controller.
  onos_port: 6653 # port of ONOS controller
  query_interval: 10
  query_base_url: "/api/v1/%query_type%?query=%query_expr%%query_params%"
  cookies: 'influx_report'

# Topics Configuration
topics:
  coordinator: "builder/coordinator"
  build_task: "build/task"
  monitor_task: "monitor/task"
  query_results: "monitor/results"


# Prometheus Configuration
prometheus:
  url: "http://host.docker.internal:9090"

queries:
  file_path: "monitoring_config/queries.yml"

# Broadcast and Socket Information
socket_info:
  inet_addr: "localhost" # IP address for socket communication
  query_send_port: 7003 # Port for sending queries
  broadcast_port: 6003 # Port for broadcasting queries

broadcast_info:
  direct_broadcast_addr: "255.255.255.255" # Broadcast address for sending messages
  limited_broadcast_addr: "255.255.255.255" # Limited broadcast address


# Logging Configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL


