# Use the official Python base image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the builderd and utils modules
COPY builderd /app/builderd
COPY utils /app/utils
COPY monitoring_config /app/monitoring_config

# Set the PYTHONPATH environment variable
ENV PYTHONPATH="/app"

# Expose necessary ports
EXPOSE 1883 8080

# Set the entrypoint to start the builderd service
ENTRYPOINT ["python", "-m", "builderd.builderd"]
