version: '3.8'

services:
  prometheus:
    image: bishwo007/prometheus:v1.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
  
  cadvisor:
    image: bishwo007/cadvisor:v1.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring-net

  node-exporter:
    - container_name: "node-exporter"
  image: "prom/node-exporter:latest"
  ports:
    "9100": "9100"
  volumes:
    "/proc": "/host/proc:ro"
    "/sys": "/host/sys:ro"
    "/": "/host/rootfs:ro"
  command:
    - "--path.procfs=/host/proc"
    - "--path.sysfs=/host/sys"
    - "--path.rootfs=/host/rootfs"
  networks:
    - "monitoring-net"

volumes:
  prometheus_data:
    driver: local

networks:
  monitoring-net:
    driver: bridge
